# 3X-UI Exporter Configuration Example
# This file contains all the configuration options available for the 3X-UI Exporter
# Command-line flags will override these settings if provided

# 3X-UI panel connection details
# Base URL of the 3X-UI panel (required)
panel-base-url: "https://your-panel-url"

# Username for 3X-UI API authentication (required)
panel-username: "your-username"

# Password for 3X-UI API authentication (required)
panel-password: "your-password"

# General settings
# Interval in seconds between updates from the panel (default: 30)
update-interval: 30

# Timezone for time-based operations (default: UTC)
timezone: "UTC"

# Metrics server configuration
# Port for the metrics server (default: 0.0.0.0)
metrics-ip: "0.0.0.0"

# Port for the metrics server (default: 9090)
metrics-port: "9090"

# Enable authentication for metrics endpoint
metrics-protected: false

# Username for metrics authentication (required if metrics-protected is true)
metrics-username: "metricsUser"

# Password for metrics authentication (required if metrics-protected is true)
metrics-password: "MetricsVeryHardPassword"
