services:
  x-ui-exporter:
    image: hteppl/x-ui-exporter:latest
    container_name: x-ui-exporter
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${METRICS_PORT:-9090}:${METRICS_PORT:-9090}"
